Angularjs/SIGN/src/SIGN.MVC/ViewModels/GuidelineViewModel.cs
using SIGN.Domain.Classes;
using SIGN.Domain.Enums;
using SIGN.Domain.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SIGN.MVC.ViewModels
{
    public class GuidelineViewModel : IModificationHistory
    {
        public int Id { get; set; }

        [Required]
        public int Number { get; set; }

        [Required]
        [StringLength(250, MinimumLength = 10)]
        public string Name { get; set; }

        public string Author { get; set; }

        public GuidelineStatus Status { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}",
               ApplyFormatInEditMode = true)]

        [Required]
        public DateTime DatePublished { get; set; }

        public DateTime DateCreated { get; set; }

        public DateTime DateModified { get; set; }

        public bool IsDirty { get; set; }

        public IEnumerable<Assessment> Assessments { get; set; }
    }
}

Angularjs/SIGN/src/SIGN.MVC/ViewModels/GuidelinesViewModel.cs
using SIGN.Domain.Classes;
using System.Collections.Generic;

namespace SIGN.MVC.ViewModels
{
    public class GuidelinesViewModel
    {
        public IEnumerable<Guideline> Guidelines { get; set; }
    }
}

Angularjs/SIGN/src/SIGN.MVC/Controllers/Web/AssessmentController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SIGN.Domain.Classes;
using SIGN.Domain.Interfaces;
using SIGN.MVC.ViewModels;
using System;

namespace SIGN.MVC.Controllers.Web
{
    /// <summary>
    /// Assessment Controller
    /// </summary>
    public class AssessmentController : Controller
    {
        private IAssessmentService _assessmentService;
        private ILogger<AssessmentController> _logger;

        public AssessmentController(
            IAssessmentService assessmentService, 
            ILogger<AssessmentController> logger)
        {
            _assessmentService = assessmentService;
            _logger = logger;
        }

        /// <summary>
        /// Displays the Assessments details view
        /// </summary>
        /// <param name="id">Assessment id</param>
        /// <returns>Assessment details view</returns>
        [Authorize]
        public IActionResult Details(int id)
        {
            try
            {
                Assessment assessment = _assessmentService.GetAssessment(id);
                AssessmentViewModel model = Mapper.Map<AssessmentViewModel>(assessment);

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error getting the assessment details page: {ex.Message}");
                return Redirect("/error");
            }
        }

        /// <summary>
        /// Displays the step view
        /// </summary>
        /// <param name="id">Step id</param>
        /// <returns>Step View</returns>
        [Authorize]
        public IActionResult Step(int id)
        {
            try
            {
                Step step = _assessmentService.GetStep(id);
                StepViewModel model = Mapper.Map<StepViewModel>(step);

                Step yesStep = _assessmentService.GetNextStep(step.Id, true);
                Step noStep = _assessmentService.GetNextStep(step.Id, false);

                if (yesStep != null)
                {
                    model.YesStepId = yesStep.Id;
                };

                if (noStep != null)
                {
                    model.NoStepId = noStep.Id;
                };

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error getting the assessment step: {ex.Message}");
                return Redirect("/error");
            }
        }
    }
}

Angularjs/SIGN/src/SIGN.MVC/Controllers/Web/GuidelineController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SIGN.Domain.Classes;
using SIGN.Domain.Interfaces;
using SIGN.MVC.ViewModels;
using System;
using System.Threading.Tasks;

namespace SIGN.MVC.Controllers.Web
{
    public class GuidelineController : Controller
    {
        private IGuidelineService _guidelineService;
        private ILogger<GuidelineController> _logger;

        public GuidelineController(
            IGuidelineService guidelineService,
            ILogger<GuidelineController> logger)
        {
            _guidelineService = guidelineService;
            _logger = logger;
        }

        [HttpGet, Authorize]
        public IActionResult AllGuidelines()
        {
            try
            {
                GuidelinesViewModel model = new GuidelinesViewModel();
                model.Guidelines = _guidelineService.GetGuidelines();
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error getting the guidelines: {ex.Message}");
                return Redirect("/error");
            }
        }

        [HttpGet, Authorize]
        public IActionResult MyGuidelines()
        {
            try
            {
                GuidelinesViewModel model = new GuidelinesViewModel();
            model.Guidelines = _guidelineService.GetMyGuidelines(User.Identity.Name);
            return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error getting the guidelines for author: {ex.Message}");
                return Redirect("/error");
            }
        }

        [HttpGet, Authorize]
        public IActionResult Details(int id)
        {
            try
            {
                Guideline guideline = _guidelineService.GetGuideline(id);
                GuidelineViewModel model = Mapper.Map<GuidelineViewModel>(guideline);
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error getting the guideline details page: {ex.Message}");
                return Redirect("/error");
            }
        }

        [HttpGet, Authorize]
        public IActionResult Add()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error getting the add guideline page: {ex.Message}");
                return Redirect("/error");
            }
        }

        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(GuidelineViewModel newGuideline)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _guidelineService.SaveGuideline(Mapper.Map<Guideline>(newGuideline));
                    return RedirectToAction("AllGuidelines");
                }

                return View(newGuideline);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error saving the guideline: {ex.Message}");
                return Redirect("/error");
            }
        }

        [HttpGet, Authorize]
        public IActionResult Edit(int id)
        {
            try
            {
                Guideline guideline = _guidelineService.GetGuideline(id);
                if (guideline == null)
                {
                    return RedirectToAction("AllGuidelines");
                }

                GuidelineViewModel model = Mapper.Map<GuidelineViewModel>(guideline);
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error getting the edit guideline page: {ex.Message}");
                return Redirect("/error");
            }
        }

        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(GuidelineViewModel guideline)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    guideline.Author = User.Identity.Name;
                    await _guidelineService.SaveGuideline(Mapper.Map<Guideline>(guideline));
                    return RedirectToAction("AllGuidelines");
                }

                return View(guideline);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error saving the guideline: {ex.Message}");
                return Redirect("/error");
            }
        }
    }
}

Angularjs/SIGN/src/SIGN.MVC/Views/Guideline/Add.cshtml
@using SIGN.Domain.Enums
@using SIGN.MVC.ViewModels
@model GuidelineViewModel
@{
    ViewBag.Title = "Add Guideline";
}

<div class="col-md-10 col-md-offset-1">
    <h3>Add New Guideline</h3>
    <form asp-action="Add" method="post" class="form-horizontal">
        <div class="form-group">
            <label for="number" class="col-md-1 form-label">Number</label>
            <div class="col-md-11">
                <input class="form-control"
                       type="number"
                       id="number"
                       name="number"
                       asp-for="Number"
                       required />
                <span asp-validation-for="Number" class="text-warning">The Number is required.</span>
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-md-1 form-label">Name</label>
            <div class="col-md-11">
                <input class="form-control" 
                       type="text" 
                       id="name" 
                       name="name" 
                       asp-for="Name" 
                       required/>
                <span asp-validation-for="Name" class="text-warning">The Name is required.</span>
            </div>
        </div>
        <div class="form-group">
            <label for="datePublished" class="col-md-1 form-label">Published</label>
            <div class="col-md-11">
                <input class="form-control" 
                       type="date" 
                       id="datePublished" 
                       name="datePublished" 
                       asp-for="DatePublished" 
                       required />
                <span asp-validation-for="DatePublished" class="text-warning">The Date published is required.</span>
            </div>
        </div>
        <div class="form-group">
            <label for="status" class="col-md-1 form-label">Status</label>
            <div class="col-md-11">
                <select class="selectpicker" id="status" name="status" asp-for="Status" required>
                    <option value="1">Current < 3 years</option>
                    <option value="2">Current 3 - 7 years</option>
                    <option value="3">> 7 years</option>
                    <option value="4">Withdrawn</option>
                    <option value="5">Recommendations being updated</option>
                </select>
                <span asp-validation-for="Status" class="text-warning">The Status is required.</span>
            </div>
        </div>
        <div>
            <input type="submit" class="btn btn-success btn-sm" value="Save" />
            <a asp-controller="Guideline" asp-action="AllGuidelines" class="btn btn-sm btn-default"><i class="fa fa-angle-left"></i> Back to Guidelines</a>
        </div>
    </form>
</div>

Angularjs/SIGN/src/SIGN.MVC/Views/Guideline/AddGuideline.cshtml
@using SIGN.Domain.Enums
@using SIGN.MVC.ViewModels
@model GuidelineViewModel
@{
    ViewBag.Title = "Add Guideline";
}

<div class="col-md-10 col-md-offset-1">
    <h3>Add New Guideline</h3>
    <form asp-action="AddGuideline" method="post" class="form-horizontal">
        <div class="form-group">
            <label for="number" class="col-md-1 form-label">Number</label>
            <div class="col-md-11">
                <input class="form-control"
                       type="number"
                       id="number"
                       name="number"
                       asp-for="Number"
                       required />
                <span asp-validation-for="Number" class="text-warning">The Number is required.</span>
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-md-1 form-label">Name</label>
            <div class="col-md-11">
                <input class="form-control" 
                       type="text" 
                       id="name" 
                       name="name" 
                       asp-for="Name" 
                       required/>
                <span asp-validation-for="Name" class="text-warning">The Name is required.</span>
                @*<span ng-show="addGuidelineForm.name.$error.minlength"
                            class="text-warning">
                        The Name must be at least 10 characters.
                    </span>*@
            </div>
        </div>
        <div class="form-group">
            <label for="datePublished" class="col-md-1 form-label">Published</label>
            <div class="col-md-11">
                <input class="form-control" 
                       type="date" 
                       id="datePublished" 
                       name="datePublished" 
                       asp-for="DatePublished" 
                       required />
                <span asp-validation-for="DatePublished" class="text-warning">The Date published is required.</span>
            </div>
        </div>
        <div class="form-group">
            <label for="status" class="col-md-1 form-label">Status</label>
            <div class="col-md-11">
                <select class="selectpicker" id="status" name="status" asp-for="Status" required>
                    <option value="1">Current < 3 years</option>
                    <option value="2">Current 3 - 7 years</option>
                    <option value="3">> 7 years</option>
                    <option value="4">Withdrawn</option>
                    <option value="5">Recommendations being updated</option>
                </select>
                <span asp-validation-for="Status" class="text-warning">The Status is required.</span>
            </div>
        </div>
        <div>
            <input type="submit" class="btn btn-success btn-sm" value="Save" />
            <a asp-controller="Guideline" asp-action="AllGuidelines" class="btn btn-sm btn-default"><i class="fa fa-angle-left"></i> Back to Guidelines</a>
        </div>
    </form>
</div>

Angularjs/SIGN/src/SIGN.MVC/Views/Guideline/AllGuidelines.cshtml
@model SIGN.MVC.ViewModels.GuidelinesViewModel
@{
    ViewBag.Title = "Guidelines";
}
<div class="col-md-10 col-md-offset-1">
    <h3>Guidelines</h3>
    <a asp-controller="Guideline" asp-action="Add" class="btn btn-sm btn-primary">Add New Guideline</a>
    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th>Number</th>
                <th>Name</th>
                <th>Date Published</th>
                <th>Status</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        @foreach (var guideline in Model.Guidelines)
        {
            <tr>
                <td>@guideline.Number</td>
                <td>@guideline.Name</td>
                <td>@guideline.DatePublished.ToString("dd/MM/yyyy")</td>
                <td>
                    @{
                        switch (guideline.Status)
                        {
                            case SIGN.Domain.Enums.GuidelineStatus.CurrentLessThanThreeYears:
                                <div title="Current < 3 yrs">
                                    <i class="fa fa-check fa-2x text-success"></i>
                                </div>
                                break;
                            case SIGN.Domain.Enums.GuidelineStatus.CurrentThreeToSevenYears:
                                <div title="Current 3 -7yrs. Some recommendations may be out of date Declaration of interests governance may not be in line with current policy">
                                    <i class="fa fa-question-circle-o fa-2x text-warning"></i>
                                </div>
                                break;
                            case SIGN.Domain.Enums.GuidelineStatus.GreaterThanSevenYears:
                                <div title=">7 yrs. Use with caution Declaration of interests governance may not be in line with current policy">
                                    <i class="fa fa-exclamation-circle fa-2x text-error"></i>
                                </div>
                                break;
                            case SIGN.Domain.Enums.GuidelineStatus.Withdrawn:
                                <div title="Withdrawn">
                                    <i class="fa fa-close fa-2x text-error"></i>
                                </div>
                                break;
                            case SIGN.Domain.Enums.GuidelineStatus.BeingUpdated:
                                <div title="Recommendations being updated">
                                    <i class="fa fa-edit fa-2x text-warning"></i>
                                </div>
                                break;
                            default:
                                break;
                        }
                    }

                </td>
                <td><a asp-controller="Guideline" asp-action="Edit" asp-route-id="@guideline.Id" class="btn btn-block btn-sm btn-success">Edit</a></td>
                <td><a asp-controller="Guideline" asp-action="Details" asp-route-id="@guideline.Id" class="btn btn-block btn-sm btn-success">View</a></td>
            </tr>
        }
    </table>
</div>

Angularjs/SIGN/src/SIGN.MVC/Views/Guideline/Details.cshtml
@model SIGN.MVC.ViewModels.GuidelineViewModel
@{
    ViewBag.Title = "Guideline Details";
}
@section scripts {
    <environment names="Development">
        <script src="~/js/accordion.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/_app/accordion.js"></script>
    </environment>
}
<div class="col-md-10 col-md-offset-1">
    <h3>Guideline Details</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>@Model.Name</h4>
                </div>
                <div class="panel-body">
                    <div class="col-md-3">
                        <p class="sign-number">@Model.Number</p>
                    </div>
                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-md-3"><p>Published</p></div>
                            <div class="col-md-9"><p>@Model.DatePublished.ToString("dd/MM/yyyy")</p></div>
                        </div>
                        <div class="row">
                            <div class="col-md-3"><p>Author</p></div>
                            <div class="col-md-9"><p>@Model.Author</p></div>
                        </div>
                        <div class="row">
                            <div class="col-md-3"><p>Status</p></div>
                            <div class="col-md-9">
                                @{
                                    switch (Model.Status)
                                    {
                                        case SIGN.Domain.Enums.GuidelineStatus.CurrentLessThanThreeYears:
                                            <div>
                                                <i class="fa fa-check text-success"></i>Current < 3 years
                                            </div>
                                            break;
                                        case SIGN.Domain.Enums.GuidelineStatus.CurrentThreeToSevenYears:
                                            <div>
                                                <i class="fa fa-question-circle-o text-warning"></i>Current 3 - 7 years
                                            </div>
                                            break;
                                        case SIGN.Domain.Enums.GuidelineStatus.GreaterThanSevenYears:
                                            <div>
                                                <i class="fa fa-exclamation-circle text-error"></i>Greater than 7 yrs
                                            </div>
                                            break;
                                        case SIGN.Domain.Enums.GuidelineStatus.Withdrawn:
                                            <div>
                                                <i class="fa fa-close text-error"></i>Withdrawn
                                            </div>
                                            break;
                                        case SIGN.Domain.Enums.GuidelineStatus.BeingUpdated:
                                            <div>
                                                <i class="fa fa-edit text-warning"></i>Recommendations being updated
                                            </div>
                                            break;
                                        default:
                                            break;
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button class="accordion">Assessments</button>
            <div class="accordion-panel">
                @foreach (var assessment in Model.Assessments)
                {
                    <div>
                        <a asp-controller="Assessment" asp-action="Details" asp-route-id="@assessment.Id" class="btn btn-block btn-primary">
                            @assessment.Name
                        </a>
                    </div>
                }
            </div>

            <button class="accordion">Recommendations</button>
            <div class="accordion-panel">
                <div>
                    <a href="#" class="btn btn-block btn-warning">
                        Recommendation 1
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

Angularjs/SIGN/src/SIGN.MVC/Views/Guideline/Edit.cshtml
@using SIGN.Domain.Enums
@using SIGN.MVC.ViewModels
@model GuidelineViewModel
@{
    ViewBag.Title = "Edit Guideline";
}

<div class="col-md-10 col-md-offset-1">
    <h3>Edit Guideline</h3>
    <form action="/guideline/edit" method="post" class="form-horizontal" asp-antiforgery="true" novalidate>
        <input name="Id"
               id="Id"
               type="hidden"
               asp-for="Id" />
        <div class="form-group">
            <label for="number" class="col-md-1 form-label">Number</label>
            <div class="col-md-11">
                <input class="form-control" 
                       type="number"
                       id="number"
                       name="number"
                       asp-for="Number"
                       required />
                <span asp-validation-for="Number" class="text-warning"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-md-1 form-label">Name</label>
            <div class="col-md-11">
                <input class="form-control"
                       type="text"
                       id="name"
                       name="name"
                       asp-for="Name"
                       required ng-minlength="10" />
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="datePublished" class="col-md-1 form-label">Published</label>
            <div class="col-md-11">
                <input class="form-control"
                       type="date"
                       id="datePublished"
                       name="datePublished"
                       asp-for="DatePublished"
                       asp-format="{0:dd/MM/yyyy}"
                       required />
                <span asp-validation-for="DatePublished" class="text-warning"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="status" class="col-md-1 form-label">Status</label>
            <div class="col-md-11">
                <select class="selectpicker" id="status" name="status" asp-for="Status" required>
                    <option value="1">Current < 3 years</option>
                    <option value="2">Current 3 - 7 years</option>
                    <option value="3">> 7 years</option>
                    <option value="4">Withdrawn</option>
                    <option value="5">Recommendations being updated</option>
                </select>
                <span asp-validation-for="Status" class="text-warning"></span>
            </div>
        </div>
        <div>
            <input type="submit" class="btn btn-success btn-sm" value="Save" />
            <a asp-controller="Guideline" asp-action="AllGuidelines" class="btn btn-sm btn-default"><i class="fa fa-angle-left"></i> Back to Guidelines</a>
        </div>
    </form>
</div>

Angularjs/SIGN/src/SIGN.MVC/Views/Guideline/EditGuideline.cshtml
@using SIGN.Domain.Enums
@using SIGN.MVC.ViewModels
@model GuidelineViewModel
@{
    ViewBag.Title = "Edit Guideline";
}

<div class="col-md-10 col-md-offset-1">
    <h3>Edit Guideline</h3>
    <form action="/guideline/editGuideline" method="post" class="form-horizontal" asp-antiforgery="true">
        <input name="Id"
               id="Id"
               type="hidden"
               asp-for="Id" />
        <div class="form-group">
            <label for="number" class="col-md-1 form-label">Number</label>
            <div class="col-md-11">
                <input class="form-control" 
                       type="number"
                       id="number"
                       name="number"
                       asp-for="Number"
                       required />
                <span asp-validation-for="Number" class="text-warning"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-md-1 form-label">Name</label>
            <div class="col-md-11">
                <input class="form-control"
                       type="text"
                       id="name"
                       name="name"
                       asp-for="Name"
                       required ng-minlength="10" />
                <span asp-validation-for="Name" class="text-warning">The Name is required.</span>

                @*<span ng-show="addGuidelineForm.name.$error.minlength"
                            class="text-warning">
                        The Name must be at least 10 characters.
                    </span>*@
            </div>
        </div>
        <div class="form-group">
            <label for="datePublished" class="col-md-1 form-label">Published</label>
            <div class="col-md-11">
                <input class="form-control"
                       type="date"
                       id="datePublished"
                       name="datePublished"
                       asp-for="DatePublished"
                       required />
                <span asp-validation-for="DatePublished" class="text-warning">The Date Published is required.</span>
            </div>
        </div>
        <div class="form-group">
            <label for="status" class="col-md-1 form-label">Status</label>
            <div class="col-md-11">
                <select class="selectpicker" id="status" name="status" asp-for="Status" required>
                    <option value="1">Current < 3 years</option>
                    <option value="2">Current 3 - 7 years</option>
                    <option value="3">> 7 years</option>
                    <option value="4">Withdrawn</option>
                    <option value="5">Recommendations being updated</option>
                </select>
                <span asp-validation-for="Status" class="text-warning">The Status is required.</span>
            </div>
        </div>
        <div>
            <input type="submit" class="btn btn-success btn-sm" value="Save" />
            <a asp-controller="Guideline" asp-action="AllGuidelines" class="btn btn-sm btn-default"><i class="fa fa-angle-left"></i> Back to Guidelines</a>
        </div>
    </form>
</div>

Angularjs/SIGN/src/SIGN.MVC/Views/Guideline/MyGuidelines.cshtml
@model SIGN.MVC.ViewModels.GuidelinesViewModel
@{
    ViewBag.Title = "My Guidelines";
}
<div class="col-md-10 col-md-offset-1">
    <h3>Guidelines created by @User.Identity.Name</h3>
    <a asp-controller="Guideline" asp-action="Add" class="btn btn-sm btn-primary">Add New Guideline</a>
    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th>Number</th>
                <th>Name</th>
                <th>Date Published</th>
                <th>Status</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        @foreach (var guideline in Model.Guidelines)
        {
            <tr>
                <td>@guideline.Number</td>
                <td>@guideline.Name</td>
                <td>@guideline.DatePublished.ToString("dd/MM/yyyy")</td>
                <td>
                    @{
                        switch (guideline.Status)
                        {
                            case SIGN.Domain.Enums.GuidelineStatus.CurrentLessThanThreeYears:
                                <i class="fa fa-check fa-2x text-success"></i>
                                break;
                            case SIGN.Domain.Enums.GuidelineStatus.CurrentThreeToSevenYears:
                                <i class="fa fa-question-circle-o fa-2x text-warning"></i>
                                break;
                            case SIGN.Domain.Enums.GuidelineStatus.GreaterThanSevenYears:
                                <i class="fa fa-exclamation-circle fa-2x text-error"></i>
                                break;
                            case SIGN.Domain.Enums.GuidelineStatus.Withdrawn:
                                <i class="fa fa-close fa-2x text-error"></i>
                                break;
                            case SIGN.Domain.Enums.GuidelineStatus.BeingUpdated:
                                <i class="fa fa-edit fa-2x text-warning"></i>
                                break;
                            default:
                                break;
                        }
                    }

                </td>
                <td><a asp-controller="Guideline" asp-action="Edit" asp-route-id="@guideline.Id" class="btn btn-block btn-sm btn-success">Edit</a></td>
                <td><a asp-controller="Guideline" asp-action="Details" asp-route-id="@guideline.Id" class="btn btn-block btn-sm btn-success">View</a></td>
            </tr>
        }
    </table>
</div>